In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('dataset/UNSW-NB15_1.csv',header = None)

C:\Users\acer\AppData\Local\Temp\ipykernel_30304\2513496729.py:1: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dataset/UNSW-NB15_1.csv',header = None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [4]:
print(df.shape)

(700001, 49)

In [5]:
print(df.isnull().sum())

0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
30         0
31         0
32         0
33         0
34         0
35         0
36         0
37         0
38         0
39         0
40         0
41         0
42         0
43         0
44         0
45         0
46         0
47    677786
48         0
dtype: int64

In [6]:
df = df.dropna(axis=1, how='all')

In [7]:
print(df.shape)

(700001, 49)

In [8]:
df.columns = [
'src_ip','src_port','dst_ip','dst_port','proto','state','duration',
'sbytes','dbytes','sttl','dttl','sloss','dloss',
'service','sload','dload','spkts','dpkts',
'swin','dwin','stcpb','dtcpb','smean','dmean',
'trans_depth','res_len','sjit','djit','stime','ltime',
'sintpkt','dintpkt','tcprtt','synack','ackdat',
'sm_ips_ports','state_ttl','http_method',
'ftp_login','ftp_cmd','srv_src','srv_dst',
'dst_ltm','src_ltm','src_dport_ltm',
'dst_sport_ltm','dst_src_ltm','attack_cat','label'
]

In [9]:
df.head()

,src_ip,src_port,dst_ip,dst_port,proto,state,duration,sbytes,dbytes,sttl,...,ftp_cmd,srv_src,srv_dst,dst_ltm,src_ltm,src_dport_ltm,dst_sport_ltm,dst_src_ltm,attack_cat,label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700001 entries, 0 to 700000
Data columns (total 49 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   src_ip         700001 non-null  object
 1   src_port       700001 non-null  object
 2   dst_ip         700001 non-null  object
 3   dst_port       700001 non-null  object
 4   proto          700001 non-null  object
 5   state          700001 non-null  object
 6   duration       700001 non-null  float64
 7   sbytes         700001 non-null  int64
 8   dbytes         700001 non-null  int64
 9   sttl           700001 non-null  int64
 10  dttl           700001 non-null  int64
 11  sloss          700001 non-null  int64
 12  dloss          700001 non-null  int64
 13  service        700001 non-null  object
 14  sload          700001 non-null  float64
 15  dload          700001 non-null  float64
 16  spkts          700001 non-null  int64
 17  dpkts          700001 non-null  int64
 18  swin           700001 non-null  int64
 19  dwin           700001 non-null  int64
 20  stcpb          700001 non-null  int64
 21  dtcpb          700001 non-null  int64
 22  smean          700001 non-null  int64
 23  dmean          700001 non-null  int64
 24  trans_depth    700001 non-null  int64
 25  res_len        700001 non-null  int64
 26  sjit           700001 non-null  float64
 27  djit           700001 non-null  float64
 28  stime          700001 non-null  int64
 29  ltime          700001 non-null  int64
 30  sintpkt        700001 non-null  float64
 31  dintpkt        700001 non-null  float64
 32  tcprtt         700001 non-null  float64
 33  synack         700001 non-null  float64
 34  ackdat         700001 non-null  float64
 35  sm_ips_ports   700001 non-null  int64
 36  state_ttl      700001 non-null  int64
 37  http_method    700001 non-null  int64
 38  ftp_login      700001 non-null  int64
 39  ftp_cmd        700001 non-null  int64
 40  srv_src        700001 non-null  int64
 41  srv_dst        700001 non-null  int64
 42  dst_ltm        700001 non-null  int64
 43  src_ltm        700001 non-null  int64
 44  src_dport_ltm  700001 non-null  int64
 45  dst_sport_ltm  700001 non-null  int64
 46  dst_src_ltm    700001 non-null  int64
 47  attack_cat     22215 non-null   object
 48  label          700001 non-null  int64
dtypes: float64(10), int64(31), object(8)
memory usage: 261.7+ MB

In [11]:
df.isnull().sum()

src_ip                0
src_port              0
dst_ip                0
dst_port              0
proto                 0
state                 0
duration              0
sbytes                0
dbytes                0
sttl                  0
dttl                  0
sloss                 0
dloss                 0
service               0
sload                 0
dload                 0
spkts                 0
dpkts                 0
swin                  0
dwin                  0
stcpb                 0
dtcpb                 0
smean                 0
dmean                 0
trans_depth           0
res_len               0
sjit                  0
djit                  0
stime                 0
ltime                 0
sintpkt               0
dintpkt               0
tcprtt                0
synack                0
ackdat                0
sm_ips_ports          0
state_ttl             0
http_method           0
ftp_login             0
ftp_cmd               0
srv_src               0
srv_dst               0
dst_ltm               0
src_ltm               0
src_dport_ltm         0
dst_sport_ltm         0
dst_src_ltm           0
attack_cat       677786
label                 0
dtype: int64

In [12]:
df = df.drop('attack_cat', axis=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700001 entries, 0 to 700000
Data columns (total 48 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   src_ip         700001 non-null  object
 1   src_port       700001 non-null  object
 2   dst_ip         700001 non-null  object
 3   dst_port       700001 non-null  object
 4   proto          700001 non-null  object
 5   state          700001 non-null  object
 6   duration       700001 non-null  float64
 7   sbytes         700001 non-null  int64
 8   dbytes         700001 non-null  int64
 9   sttl           700001 non-null  int64
 10  dttl           700001 non-null  int64
 11  sloss          700001 non-null  int64
 12  dloss          700001 non-null  int64
 13  service        700001 non-null  object
 14  sload          700001 non-null  float64
 15  dload          700001 non-null  float64
 16  spkts          700001 non-null  int64
 17  dpkts          700001 non-null  int64
 18  swin           700001 non-null  int64
 19  dwin           700001 non-null  int64
 20  stcpb          700001 non-null  int64
 21  dtcpb          700001 non-null  int64
 22  smean          700001 non-null  int64
 23  dmean          700001 non-null  int64
 24  trans_depth    700001 non-null  int64
 25  res_len        700001 non-null  int64
 26  sjit           700001 non-null  float64
 27  djit           700001 non-null  float64
 28  stime          700001 non-null  int64
 29  ltime          700001 non-null  int64
 30  sintpkt        700001 non-null  float64
 31  dintpkt        700001 non-null  float64
 32  tcprtt         700001 non-null  float64
 33  synack         700001 non-null  float64
 34  ackdat         700001 non-null  float64
 35  sm_ips_ports   700001 non-null  int64
 36  state_ttl      700001 non-null  int64
 37  http_method    700001 non-null  int64
 38  ftp_login      700001 non-null  int64
 39  ftp_cmd        700001 non-null  int64
 40  srv_src        700001 non-null  int64
 41  srv_dst        700001 non-null  int64
 42  dst_ltm        700001 non-null  int64
 43  src_ltm        700001 non-null  int64
 44  src_dport_ltm  700001 non-null  int64
 45  dst_sport_ltm  700001 non-null  int64
 46  dst_src_ltm    700001 non-null  int64
 47  label          700001 non-null  int64
dtypes: float64(10), int64(31), object(7)
memory usage: 256.3+ MB

In [14]:
df = df.drop(['src_ip', 'dst_ip'], axis=1)

In [15]:
import numpy as np
def convert_port(x):
    try:
        x = str(x).strip()
        if x == '-' or x == '':
            return np.nan 
        if x.startswith('0x'):
            return int(x, 16)
        return int(x)
    except:
        return np.nan   
df['src_port'] = df['src_port'].apply(convert_port)
df['dst_port'] = df['dst_port'].apply(convert_port)

In [16]:
df[['src_port','dst_port']].isna().sum()

src_port    2
dst_port    7
dtype: int64

In [17]:
df.dropna(subset=['src_port', 'dst_port'], inplace=True)

In [18]:
df['src_port'] = df['src_port'].astype(int)
df['dst_port'] = df['dst_port'].astype(int)

In [19]:
df[['src_port','dst_port']].isna().sum()
df.shape

(699992, 46)

In [20]:
df.columns

Index(['src_port', 'dst_port', 'proto', 'state', 'duration', 'sbytes',
       'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'sload', 'dload',
       'spkts', 'dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smean', 'dmean',
       'trans_depth', 'res_len', 'sjit', 'djit', 'stime', 'ltime', 'sintpkt',
       'dintpkt', 'tcprtt', 'synack', 'ackdat', 'sm_ips_ports', 'state_ttl',
       'http_method', 'ftp_login', 'ftp_cmd', 'srv_src', 'srv_dst', 'dst_ltm',
       'src_ltm', 'src_dport_ltm', 'dst_sport_ltm', 'dst_src_ltm', 'label'],
      dtype='object')

In [21]:
df['label'].value_counts()

label
0    677777
1     22215
Name: count, dtype: int64

In [22]:
df = pd.get_dummies(df, columns=['proto', 'state', 'service'], drop_first=True)

In [23]:
x = df.drop('label', axis=1)
y = df['label']

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2,random_state=42,stratify=y)

In [25]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)
model.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [26]:
y_pred = model.predict(x_test)

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    135556
           1       0.97      0.98      0.97      4443

    accuracy                           1.00    139999
   macro avg       0.99      0.99      0.99    139999
weighted avg       1.00      1.00      1.00    139999

In [28]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[135434    122]
 [   110   4333]]

In [29]:
y_prob = model.predict_proba(x_test)[:,1]
y_pred_custom = (y_prob > 0.4).astype(int)

In [30]:
print(confusion_matrix(y_test, y_pred_custom))
print(classification_report(y_test, y_pred_custom))

[[135356    200]
 [    43   4400]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    135556
           1       0.96      0.99      0.97      4443

    accuracy                           1.00    139999
   macro avg       0.98      0.99      0.99    139999
weighted avg       1.00      1.00      1.00    139999

In [31]:
import os
print(os.getcwd())

C:\Users\acer\NETMON

In [32]:
print(os.listdir())

['.ipynb_checkpoints', 'dataset', 'ntamodel.ipynb']

In [34]:
import os
os.chdir(r"C:\Users\acer\NETMON")
print(os.getcwd())

C:\Users\acer\NETMON

In [35]:
import os
print(os.listdir(".."))

['.ai-navigator', '.anaconda', '.BigNox', '.codex', '.conda', '.condarc', '.continuum', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.junie', '.jupyter', '.mamba', '.matplotlib', '.python_history', '.spyder-py3', '.streamlit', '.VirtualBox', '.virtual_documents', '.vscode', 'abc.py', 'abc.txt', 'anaconda3', 'anaconda_projects', 'AppData', 'Application Data', 'Boston_project', 'CodeBlocks', 'Contacts', 'Cookies', 'CrossDevice', 'data', 'Dataset', 'day 1.ipynb', 'Day 2.ipynb', 'day 5 practical.py', 'Diabets', 'Documents', 'Downloads', 'Favorites', 'GNS3', 'index.ipynb', 'inst.ini', 'internship', 'inventory.db', 'Jedi', 'kmeans_clustering.ipynb', 'KMeans_project - Copy (2).ipynb', 'Links', 'Local Settings', 'Magnus_Ideas_Internship', 'matplotlipday13.ipynb', 'movies.pr', 'movie_dict.pkl', 'movie_dict_.pkl', 'My Documents', 'myfunctions.py', 'NetHood', 'NETMON', 'new project', 'neww', 'NTA', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{eb6f9dd1-9097-11ef-b441-ef3f2a26f939}.TM.blf', 'NTUSER.DAT{eb6f9dd1-9097-11ef-b441-ef3f2a26f939}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{eb6f9dd1-9097-11ef-b441-ef3f2a26f939}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'numpy1.ipynb', 'numpydetial.ipynb', 'numpydetial.zip', 'numpypractice1.ipynb', 'nuuid.ini', 'OneDrive', 'pandas.ipynb', 'pandasday10.ipynb', 'practice.py', 'PrintHood', 'proj_creditcard', 'PyCharmMiscProject', 'PycharmProjects', 'qp dbm.pdf', 'qusstonpaper dbm.pdf', 'Recent', 'saga_gui.ini', 'Saved Games', 'seabornday13.ipynb', 'Searches', 'SendTo', 'similarty.pkl', 'sql', 'Start Menu', 'static', 'Templates', 'tmdb_5000_credits.csv', 'tmdb_5000_movies.csv', 'today.ipynb', 'Untitled Folder', 'Untitled-1.py', 'Untitled-1.txt', 'Untitled.ipynb', 'untitled.py', 'Untitled1.ipynb', 'untitled1.py', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'useruid.ini', 'VirtualBox VMs', 'vmlogs', 'whitewine', 'whitewine - Copy', 'WPS Cloud Files']

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [41]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [42]:
import joblib

joblib.dump(model, "traffic_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

['label_encoder.pkl']